require: rubocop-rspec

AllCops:
  Exclude:
    - '.internal_test_app/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/generators/warclight/templates/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Metrics/AbcSize:
  Exclude:
    - app/controllers/collections_controller.rb
    - app/helpers/collections_helper.rb
    - app/helpers/wasapi_files_helper.rb
    - app/jobs/collections_cat_job.rb
    - app/jobs/collections_graphpass_job.rb
    - app/jobs/collections_spark_job.rb
    - app/jobs/wasapi_files_download_job.rb
    - app/jobs/wasapi_files_populate_job.rb

Metrics/BlockLength:
  Exclude:
    - app/jobs/collections_spark_job.rb
    - app/jobs/wasapi_files_download_job.rb
    - app/jobs/wasapi_files_populate_job.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/environments/test.rb

Metrics/MethodLength:
  Exclude:
    - app/controllers/collections_controller.rb
    - app/helpers/collections_helper.rb
    - app/jobs/collections_cat_job.rb
    - app/jobs/collections_graphpass_job.rb
    - app/jobs/collections_spark_job.rb
    - app/jobs/wasapi_files_download_job.rb
    - app/jobs/wasapi_files_populate_job.rb

Metrics/LineLength:
  Exclude:
    - app/helpers/users_helper.rb
    - app/jobs/collections_cat_job.rb
    - app/jobs/collections_graphpass_job.rb
    - app/jobs/collections_spark_job.rb
    - app/jobs/wasapi_files_populate_job.rb
    - test/helpers/users_helper_test.rb

Rails:
  Enabled: true

RSpec/NestedGroups:
  Max: 4

Rails/FilePath:
  Exclude:
    - config/environments/development.rb

Style/AlignArray:
  Exclude:
    - app/controllers/collections_controller.rb
    - app/jobs/wasapi_files_populate_job.rb

Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb

Style/GuardClause:
  Exclude:
    - app/helpers/collections_helper.rb
    - app/helpers/wasapi_files_helper.rb
    - app/jobs/collections_spark_job.rb
    - app/jobs/wasapi_files_populate_job.rb

Style/IfUnlessModifier:
  Exclude:
    - app/controllers/sessions_controller.rb
    - app/helpers/wasapi_files_helper.rb

Style/NegatedIf:
  Exclude:
    - app/jobs/wasapi_files_download_job.rb

Style/Next:
  Exclude:
    - app/jobs/wasapi_files_download_job.rb
    - app/jobs/wasapi_files_populate_job.rb

Style/PercentLiteralDelimiters:
  Exclude:
    - config/spring.rb

Style/PredicateName:
  Exclude:
    - test/test_helper.rb
