require: rubocop-rspec

AllCops:
  Exclude:
    - '.internal_test_app/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/generators/warclight/templates/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Rails:
  Enabled: true

RSpec/NestedGroups:
  Max: 4

Rails/FilePath:
  Exclude:
    - config/environments/development.rb

Style/PercentLiteralDelimiters:
  Exclude:
    - config/spring.rb

Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb

Style/IfUnlessModifier:
  Exclude:
    - app/controllers/sessions_controller.rb

Metrics/AbcSize:
  Exclude:
    - app/jobs/wasapi_files_populate_job.rb

Metrics/MethodLength:
  Exclude:
    - app/jobs/wasapi_files_populate_job.rb
    - app/controllers/collections_controller.rb

Metrics/LineLength:
  Exclude:
    - app/helpers/users_helper.rb

Style/GuardClause:
  Exclude:
    - app/jobs/wasapi_files_populate_job.rb

Metrics/BlockLength:
  Exclude:
    - app/jobs/wasapi_files_populate_job.rb

Layout/AlignArray:
  Exclude:
    - app/jobs/wasapi_files_populate_job.rb
    - app/controllers/collections_controller.rb
