require: rubocop-rspec

AllCops:
  Exclude:
    - '.internal_test_app/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/generators/warclight/templates/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Layout/AlignArray:
  Exclude:
    - app/controllers/collections_controller.rb
    - app/jobs/wasapi_seed_job.rb

Metrics/AbcSize:
  Exclude:
    - app/controllers/collections_controller.rb
    - app/helpers/collections_helper.rb
    - app/helpers/dashboards_helper.rb
    - app/helpers/wasapi_files_helper.rb
    - app/jobs/cleanup_job.rb
    - app/jobs/graphpass_job.rb
    - app/jobs/spark_job.rb
    - app/jobs/textfilter_job.rb
    - app/jobs/wasapi_download_job.rb
    - app/jobs/wasapi_seed_job.rb

Metrics/BlockLength:
  Exclude:
    - app/jobs/spark_job.rb
    - app/jobs/textfilter_job.rb
    - app/jobs/wasapi_download_job.rb
    - app/jobs/wasapi_seed_job.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/environments/test.rb
    - config/routes.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - app/helpers/wasapi_files_helper.rb

Metrics/LineLength:
  Exclude:
    - app/helpers/users_helper.rb
    - app/jobs/cleanup_job.rb
    - app/jobs/graphpass_job.rb
    - app/jobs/spark_job.rb
    - app/jobs/textfilter_job.rb
    - app/jobs/wasapi_seed_job.rb
    - app/mailers/user_mailer.rb
    - test/controllers/dashboards_controller_test.rb
    - test/controllers/pages_controller_test.rb
    - test/helpers/auth_helper.rb
    - test/helpers/users_helper_test.rb

Metrics/MethodLength:
  Exclude:
    - app/controllers/collections_controller.rb
    - app/helpers/collections_helper.rb
    - app/helpers/dashboards_helper.rb
    - app/helpers/wasapi_files_helper.rb
    - app/jobs/cleanup_job.rb
    - app/jobs/graphpass_job.rb
    - app/jobs/spark_job.rb
    - app/jobs/textfilter_job.rb
    - app/jobs/wasapi_download_job.rb
    - app/jobs/wasapi_seed_job.rb

Metrics/ModuleLength:
  Exclude:
    - app/helpers/dashboards_helper.rb

Metrics/PerceivedComplexity:
  Exclude:
    - app/helpers/wasapi_files_helper.rb

Naming/AccessorMethodName:
    Exclude:
      - app/helpers/dashboards_helper.rb

Naming/PredicateName:
  Exclude:
    - test/test_helper.rb

Rails:
  Enabled: true

RSpec/NestedGroups:
  Max: 4

Rails/FilePath:
  Exclude:
    - config/environments/development.rb

Rails/HasManyOrHasOneDependent:
  Exclude:
    - app/models/collection.rb
    - app/models/user.rb

Rails/HttpPositionalArguments:
  Exclude:
    - test/controllers/dashboards_controller_test.rb

Security/Open:
  Exclude:
    - app/jobs/wasapi_download_job.rb

Style/BlockDelimiters:
  Exclude:
    - app/helpers/dashboards_helper.rb

Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb

Style/GuardClause:
  Exclude:
    - app/helpers/collections_helper.rb
    - app/helpers/wasapi_files_helper.rb
    - app/jobs/spark_job.rb
    - app/jobs/wasapi_seed_job.rb
    - app/models/concerns/ai_wasapi_validator.rb

Style/IfUnlessModifier:
  Exclude:
    - app/controllers/sessions_controller.rb
    - app/helpers/wasapi_files_helper.rb

Style/NegatedIf:
  Exclude:
    - app/jobs/wasapi_download_job.rb

Style/Next:
  Exclude:
    - app/jobs/textfilter_job.rb
    - app/jobs/wasapi_download_job.rb
    - app/jobs/wasapi_seed_job.rb

Style/PercentLiteralDelimiters:
  Exclude:
    - config/spring.rb

Style/RedundantSelf:
  Exclude:
    - config/initializers/delayed_job_config.rb

Style/RescueStandardError:
  Exclude:
    - app/jobs/wasapi_download_job.rb

Style/StringLiterals:
  Exclude:
    - test/controllers/dashboards_controller_test.rb
