sudo: false
language: ruby
notifications:
  email: false
branches:
  only:
    - master
before_install:
  - nvm install node
  - npm install
before_script:
  - cp config/application.yml.example config/application.yml
rvm:
  - 2.5.7
  - 2.6.5
cache: bundler
script: bundle exec rake
