sudo: false
language: ruby
notifications:
  email: false
before_install:
  - nvm install node
  - npm install
before_script:
  - cp config/application.yml.example config/application.yml
rvm:
  - 2.4.5
  - 2.3.8
cache: bundler
script: bundle exec rake
