sudo: false
language: ruby
notifications:
  email: false
before_install:
  - nvm install node
  - npm install
before_script:
  - cp config/application.yml.example config/application.yml
  - mkdir /tmp/travis
rvm:
  - 2.4.2
  - 2.3.5
  - 2.2.8
cache: bundler
script: bundle exec rake
