name: AUK Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Setup Node
        run: npm install
      - name: Setup auk config
        run: cp config/application.yml.example config/application.yml
      - name: Setup auk
        run: bundle install
      - name: Run tests
        run: bundle exec rake
      - name: Upload coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash)
